name: "Release"
on:
  push:
    tags:
      - v**
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
      - name: Hackage release
        uses: cachix/haskell-release-action@v1
        with:
          - hackage-token: "${{ secrets.HACKAGE_AUTH_TOKEN }}"
