name: "Release"
on:
  push:
    tags:
      - v**
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hackage release
        uses: cachix/haskell-release-action@v1
        with:
          - hackage-token: ${{ secrets.HACKAGE_AUTH_TOKEN }}
